server:
    # forward-headers-strategy: native
    port: 8058

spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: ${GIT_URI}
                    username: ${GIT_USERNAME}
                    password: ${GIT_TOKEN}
                    default-label: main
                    search-paths:
                        - "{application}"
                        - "{application}/{profile}"
    profiles:
        active: git # Git을 사용하여 설정을 불러옴

    devtools:
        restart:
            enabled: true

management:
    endpoints:
        web:
            exposure:
                include: health, info, refresh, env, beans
    endpoint:
        health:
            show-details: always
